-- Outbound gate ledger: the halt rows, send caps, dedupe keys and actor
-- attribution that lib/outbound-gate.js reads and writes.
--
-- ONE TABLE ON PURPOSE. The hardening audit (2026-09-02, section 6) explicitly
-- cut "four separate new library files" in favour of one module and one table:
-- four controls that must agree with each other are cheaper to reason about,
-- and to halt, when they share a ledger.
--
-- ROW KINDS
--   kind = 'halt'   per-account kill switch. active=true stops that tenant's
--                   customer-facing sends. The GLOBAL kill switch is the env
--                   flag LIGHTDECK_OUTBOUND_HALT and needs no row, so it still
--                   works when the database is unreachable.
--   kind = 'send'   one row per customer-facing message that actually left,
--                   carrying the dedupe key and the response to replay, the
--                   salted recipient hash for the per-recipient cooldown, and
--                   the actor block.
--   kind = 'action' a side effect that is not a message but must stay
--                   attributable: mark paid, void, accept, team invite.
--
-- ADDITIVE AND IDEMPOTENT. Nothing here alters an existing object, and the
-- application tolerates this table being absent (it degrades caps/dedupe and
-- logs LD_OUTBOUND_GATE_DEGRADED; the env halt flag keeps working), so this can
-- be applied by hand before or after the code deploys.
--
-- LOCKDOWN PATTERN matches scripts/migrations/2026-08-26-support-tickets.sql:
-- RLS enabled AND forced, anon/authenticated revoked, service_role granted. The
-- app reaches this table only through the service-role server boundary; no
-- browser has, or should have, a path to the send ledger.

BEGIN;

CREATE TABLE IF NOT EXISTS public.outbound_gate (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL,
  account_id text NOT NULL,
  channel text NOT NULL DEFAULT '',
  document_key text,
  recipient_hash text,
  dedupe_key text,
  response jsonb,
  actor jsonb,
  reason text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Dedupe replay: one row may own a key. Partial so the millions of rows with no
-- key (actor rows, halt rows) never enter the index.
CREATE UNIQUE INDEX IF NOT EXISTS outbound_gate_dedupe_key_idx
  ON public.outbound_gate (dedupe_key)
  WHERE dedupe_key IS NOT NULL;

-- Daily cap + per-recipient cooldown are both "rows for this account and
-- channel since <timestamp>".
CREATE INDEX IF NOT EXISTS outbound_gate_window_idx
  ON public.outbound_gate (account_id, channel, created_at DESC);

-- Per-account halt lookup runs on every send, so it gets its own narrow index.
CREATE INDEX IF NOT EXISTS outbound_gate_halt_idx
  ON public.outbound_gate (account_id)
  WHERE kind = 'halt' AND active;

ALTER TABLE public.outbound_gate ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.outbound_gate FORCE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.outbound_gate FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.outbound_gate_id_seq FROM anon, authenticated;
GRANT ALL ON TABLE public.outbound_gate TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.outbound_gate_id_seq TO service_role;

COMMIT;

-- HALT ONE TENANT (owner runbook; the global flag is an env var, not SQL):
--   INSERT INTO public.outbound_gate (kind, account_id, reason)
--   VALUES ('halt', '<account-id>', 'Paused while we work out what sent those.');
-- RELEASE THAT TENANT:
--   UPDATE public.outbound_gate SET active = false
--    WHERE kind = 'halt' AND account_id = '<account-id>';
