-- Durable beta support inbox. The app already writes this table through the
-- service-role-only /api/support boundary; this migration removes the manual
-- environment drift that left Preview without the table.

BEGIN;

CREATE TABLE IF NOT EXISTS public.support_tickets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id text NOT NULL,
  email text,
  type text NOT NULL,
  subject text NOT NULL,
  message text NOT NULL,
  status text NOT NULL DEFAULT 'open',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz
);

CREATE INDEX IF NOT EXISTS support_tickets_account_id_idx
  ON public.support_tickets (account_id);
CREATE INDEX IF NOT EXISTS support_tickets_created_at_idx
  ON public.support_tickets (created_at DESC);

ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets FORCE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.support_tickets FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.support_tickets_id_seq FROM anon, authenticated;
GRANT ALL ON TABLE public.support_tickets TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.support_tickets_id_seq TO service_role;

COMMIT;
